work_dir: ${hydra:runtime.cwd}
save_dir: ${hydra:run.dir}

defaults:
  - data_paths: default_ithaca365.yaml
  - _self_

dataset: lyft
resave: True
sample_path: /share/campbell/lyft/info_ithaca365/all_samples.csv
lidar_sample_data_path: /share/campbell/lyft/info/all_lidar_sample_data_samples_ithaca365.txt

covariance_id: 3
use_angular_velocity: False
match_distance: m
match_threshold: 14.0671
match_algorithm: greedy