ldls_mask_path: /share/campbell/lyft/ldls_masks
ldls_full_mask_path: /share/campbell/lyft/ldls_full_masks
ldls_box_path: /share/campbell/lyft/ldls_boxes
ldls_full_box_path: /share/campbell/lyft/ldls_full_boxes
ldls_track_path: /share/campbell/lyft/track_lists
ldls_sample_path: /share/campbell/lyft/info
matched_scenes_path: /share/campbell/lyft/info